version: 2.15.1
services:
  postgres:
    image: postgres:latest
    container_name: postgres     
    expose:
    - 5432
    ports:
      - 5432:5432
    restart: unless-stopped
# APP*****************************************
  springbootapp:
    image: springbootapp
    build: ./
    container_name: springbootapp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
volumes:
  postgres-data: